version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Building...
      - npm install
      - npm run build
artifacts:
  type: zip
  files:
    - 'dist/ByjusJobSearchApp/**/*'