version: 0.2

phases:
install:
  runtime-versions:
    node: 12
  commands:
    - npm install
    - npm run build
    - zip -r build.zip dist/*
build:
  commands:
    - echo Building...
artifacts:
  files:
    - './build.zip'